name: Publish Testnet Images

on:
  push:
    branches: develop

jobs:
  testnet:
    name: testnet
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build images
        run: |
          make CHAINNET=testnet BINARY=ebrelayer build-image

      - name: Push images
        run: |
          docker push sifchain/ebrelayer:testnet
